### PR TITLE
Initial setup - next try 

### LINKED ISSUE #1: Stub out repo with default content
Let's add MAINTAINERS, LICENSE, Makefile, README to start.  Base this on the service-node-red or service-homeassistant repos.

### PR DESCRIPTION
**Pull request by jwende**
initial version - I hope that I fixed all open items ...

### CODE REVIEW

**Comment by joewxboy** [comment]
Looks good.  Once you amend your commits to add a signoff (see the ones with the red X beside them above), we can merge.

**Comment by t-fine** [comment]
Hello @jwende thanks for your contribution! Could you please squash the 16 commits to one single commit and give it a good summary commit message, and add the `-s` DCO sign-off with your single commit? Thanks!

**Comment by jwende** [comment]
Can I do this here or in my fork and send a new pull request?

**Comment by jwende** [comment]
did a squash and added a new commit message - I hope it looks better now.
J.

**Comment by t-fine** [comment]
@jwende excellent, thank you!

**Pull request merged**
